/**:
    ros__parameters:
      path: Costa_diagnostics
      sensors:
        type: diagnostic_aggregator/AnalyzerGroup
        path: Sensors
        analyzers:
          cameras:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Cameras
            contains: [ 'd435i' ]
          lidar3d:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Lidar3D
            contains: [ 'lidar3d' ]
          lidar2d:
            type: diagnostic_aggregator/GenericAnalyzer
            path: LIDAR2D
            contains: [ 'scan' ] 
          imu:
            type: diagnostic_aggregator/GenericAnalyzer
            path: IMU
            contains: [ 'data_raw' ]
          gps:
            type: diagnostic_aggregator/GenericAnalyzer
            path: GPS
            contains: [ 'gps' ]
      cpu:
        type: diagnostic_aggregator/GenericAnalyzer
        path: CPU_State
        contains: [ 'cpu_monitor'] 
      ram:
        type: diagnostic_aggregator/GenericAnalyzer
        path: RAM_State
        contains: [ 'ram_monitor']
      hd:
        type: diagnostic_aggregator/GenericAnalyzer
        path: HD_State
        contains: [ 'hd_monitor']
      battery:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Batteries
        contains: [ 'Battery' ]
      # lidar2d:
      #     type: diagnostic_aggregator/GenericAnalyzer
      #     path: LIDAR2D
      #     contains: [ 'scan' ] 

            

          