/**:
  analyzers:
    ros__parameters:
      path: Diagnostics
      battery:
        type: diagnostic_aggregator/AnalyzerGroup
        path: Batteries
        analyzers:
          battery:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Battery_State
            contains: [ 'Battery' ]

  analyzers:
    ros__parameters:
      path: Costa_diagnostics
      sensors:
        type: diagnostic_aggregator/AnalyzerGroup
        path: Sensors
        analyzers:
          cameras:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Cameras
            contains: [ 'camera' ]
          lidar2d:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Lidar2D
            contains: [ 'lidar2d' ]
          lidar3d:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Lidar3D
            contains: [ 'lidar3d' ]
          imu:
            type: diagnostic_aggregator/GenericAnalyzer
            path: IMU
            contains: [ 'data_raw' ]
          gps:
            type: diagnostic_aggregator/GenericAnalyzer
            path: GPS
            contains: [ 'gps' ]
      cpu:
        type: diagnostic_aggregator/GenericAnalyzer
        path: CPU_State
        contains: [ 'cpu_monitor'] 

            

          