serial_number: j100-0000
version: 0
system:
  username: administrator
  ros2:
    namespace: misskal
    domain_id: 0
    rmw_implementation: rmw_fastrtps_cpp
    workspaces: []
platform:
  controller: ps4
  battery:
    model: HE2613
    configuration: S1P1
  attachments:
    - name: front_fender
      type: fender
    - name: rear_fender
      type: fender
      rpy: [0.0, 0.0, 3.1415]
  extras:
    urdf: null
    ros_parameters:
      linear.x.max_velocity": 2.0
      linear.x.min_velocity": -2.0
      linear.x.max_acceleration": 20.0
      linear.x.min_acceleration": -20.0
      angular.z.max_velocity": 4.0
      angular.z.min_velocity": -4.0
      angular.z.max_acceleration": 25.0
      angular.z.min_acceleration": -25.0
links:
  box: []
  cylinder: []
  frame: []
  mesh: []
  sphere: []
mounts:
  bracket: []
  fath_pivot: []
  riser: []
  disk: []
  post: []
sensors:
  camera: []
  gps: []
  imu: []
  lidar2d: []
  lidar3d: []
=======
serial_number: j100-0000
version: 0
system:
  hosts:
    - hostname: cpr-j100-0000
      ip: 192.168.131.1
  ros2:
    namespace: j100_0000
platform:
  attachments:
    - name: front_fender
      type: j100.fender
    - name: rear_fender
      type: j100.fender
      rpy: [0.0, 0.0, 3.1415]
